import { useMemo,useState } from "react";
import { Link } from "react-router-dom";
import { AppLayout } from "@/components/AppLayout";
import { datasets,getDataset } from "@/data/datasets";
import { buildEvidenceBundle,buildHypotheses } from "@/lib/discoveryEngine";
import { LivingCell,cellRegions } from "@/components/LivingCell";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { ArrowRight,Atom,BrainCircuit,ChevronRight,Dna,FlaskConical,Network,Search,ShieldCheck,Sparkles } from "lucide-react";
const Index=()=>{const [datasetId,setDatasetId]=useState(datasets[0].id);const [selected,setSelected]=useState("mito-a");const dataset=getDataset(datasetId)??datasets[0];const evidence=useMemo(()=>buildEvidenceBundle(dataset),[dataset]);const hypotheses=useMemo(()=>buildHypotheses(dataset),[dataset]);const region=cellRegions.find(r=>r.id===selected)??cellRegions[0];
return <AppLayout><main className="home-instrument"><section className="instrument-shell"><header className="instrument-topbar"><div><div className="instrument-brand"><span className="brand-dot"/>NETWORK PULSE <span>· CELL ATLAS</span></div><div className="instrument-sub">INSIDE ONE SYSTEM · EVERY CLAIM TRACEABLE</div></div><div className="instrument-readouts"><div><span>SYSTEMS</span><strong>14/14</strong></div><div><span>EVIDENCE</span><strong>{evidence.length}</strong></div><div><span>HYPOTHESES</span><strong>{hypotheses.length}</strong></div><div><span>PROVENANCE</span><strong>100%</strong></div></div></header>
<div className="instrument-grid"><aside className="instrument-rail left-rail"><div className="rail-label">BIOLOGICAL SYSTEMS</div>{cellRegions.map(r=><button key={r.id} onClick={()=>setSelected(r.id)} className={"system-button "+(selected===r.id?"active":"")}><span>{r.name}</span><small>{r.signal}%</small></button>)}<div className="rail-divider"/><div className="rail-label">ACTIVE COHORT</div><Select value={datasetId} onValueChange={setDatasetId}><SelectTrigger className="w-full bg-black/20"><SelectValue/></SelectTrigger><SelectContent>{datasets.map(d=><SelectItem key={d.id} value={d.id}>{d.name}</SelectItem>)}</SelectContent></Select></aside>
<div className="cell-viewport"><div className="viewport-label"><span>FULL ROTATION</span><span>THE WHOLE CELL</span></div><LivingCell selected={selected} onSelect={setSelected}/><div className="viewport-title"><span className="eyebrow">BIOLOGY, INTERROGATED.</span><h1>Follow the signal.<br/>Challenge the mechanism.</h1></div><div className="zoom-readout">1.05× <span>● ○ ○</span></div></div>
<aside className="instrument-rail right-rail"><div className="rail-label">SELECTED SYSTEM</div><div className="selected-system"><Atom className="h-5 w-5"/><h2>{region.name}</h2><p>{region.subtitle}</p></div><div className="mini-metric"><span>Signal</span><strong>{region.signal}%</strong><i style={{width:region.signal+"%"}}/></div><div className="mini-metric"><span>Linked pathway</span><strong>{region.pathway}</strong></div><div className="rail-divider"/><div className="rail-label">DESCEND INTO</div>{[["Pathway","/workspace",Network],["Evidence","/evidence",ShieldCheck],["Hypotheses","/discovery",BrainCircuit],["Perturbation","/simulate",FlaskConical]].map(([label,to,I])=><Link key={String(label)} to={String(to)} className="descent-link"><I className="h-4 w-4"/><span>{label}</span><ChevronRight className="h-4 w-4 ml-auto"/></Link>)}</aside></div>
<footer className="instrument-console"><div className="console-status"><span className="live-dot"/> LIVE EVIDENCE STATE <b>{dataset.shortName}</b><span>{dataset.source}</span></div><div className="console-command"><Search className="h-4 w-4"/><span>What do you want to understand?</span><Button size="sm" asChild><Link to="/discovery">Investigate <ArrowRight className="ml-1 h-3.5 w-3.5"/></Link></Button></div><div className="console-trace"><svg viewBox="0 0 180 34" preserveAspectRatio="none"><polyline points="0,22 12,21 24,23 36,17 48,19 60,11 72,18 84,15 96,16 108,9 120,14 132,12 144,17 156,10 168,13 180,8" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg></div></footer></section>
<section className="home-depth"><div><p className="eyebrow">ONE BIOLOGICAL OBJECT · MANY REPRESENTATIONS</p><h2>The homepage is the topmost zoom level.</h2><p>Start with the living system. Descend through organelle, pathway, network, protein, evidence, hypothesis and experiment without losing provenance.</p></div><div className="depth-chain">{["Cell","Organelle","Pathway","Network","Protein","Evidence","Hypothesis","Experiment"].map((x,i)=><div key={x}><Badge variant={i===0?"default":"outline"}>{x}</Badge>{i<7&&<ChevronRight className="h-3 w-3"/>}</div>)}</div><div className="depth-actions"><Button asChild><Link to="/discovery"><Sparkles className="mr-2 h-4 w-4"/>Open Discovery OS</Link></Button><Button variant="outline" asChild><Link to="/evidence"><Dna className="mr-2 h-4 w-4"/>Audit the evidence</Link></Button></div></section></main></AppLayout>};export default Index;
