import { useMemo, useState } from "react";
import { AppLayout } from "@/components/AppLayout";
import { datasets, getDataset } from "@/data/datasets";
import { rankGenesByNetworkInfluence, simulateNodeRemoval } from "@/lib/discoveryEngine";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Orbit, Network, Activity, GitBranch, RotateCcw, FlaskConical, Crosshair } from "lucide-react";

const Simulate=()=>{
 const [datasetId,setDatasetId]=useState(datasets[0].id); const dataset=getDataset(datasetId)??datasets[0]; const ranked=useMemo(()=>rankGenesByNetworkInfluence(dataset),[dataset]);
 const [target,setTarget]=useState(dataset.genes[0].symbol); const [applied,setApplied]=useState(false); const result=useMemo(()=>simulateNodeRemoval(dataset,target),[dataset,target]);
 const choose=(id:string)=>{const d=getDataset(id)??datasets[0];setDatasetId(id);setTarget(d.genes[0].symbol);setApplied(false)};
 return <AppLayout><div className="container max-w-[1500px] py-10 space-y-6"><div className="flex flex-col xl:flex-row xl:items-end justify-between gap-5"><div><p className="eyebrow">Counterfactual laboratory</p><h1 className="mt-2 text-4xl md:text-5xl font-semibold">Break the network on purpose.</h1><p className="mt-3 max-w-3xl text-muted-foreground">Remove a node, recompute topology, expose first order consequences, then define the measurement that could prove the model wrong.</p></div><div className="flex flex-wrap gap-2"><Select value={datasetId} onValueChange={choose}><SelectTrigger className="w-[240px]"><SelectValue/></SelectTrigger><SelectContent>{datasets.map(d=><SelectItem key={d.id} value={d.id}>{d.name}</SelectItem>)}</SelectContent></Select><Select value={target} onValueChange={v=>{setTarget(v);setApplied(false)}}><SelectTrigger className="w-[180px]"><SelectValue/></SelectTrigger><SelectContent>{ranked.map(g=><SelectItem key={g.symbol} value={g.symbol}>{g.symbol}</SelectItem>)}</SelectContent></Select><Button onClick={()=>setApplied(true)}><Orbit className="mr-2 h-4 w-4"/>Perturb</Button></div></div>
 <div className="grid md:grid-cols-4 gap-3">{[["Original edges",dataset.edges.length,Network],["Edges lost",applied?result.removedEdges.length:0,GitBranch],["Connectivity loss",applied?Math.round(result.connectivityLoss*100)+"%":"0%",Activity],["Pathways touched",applied?result.affectedPathways.length:0,FlaskConical]].map(([l,v,I])=><Card key={String(l)}><CardContent className="p-5"><div className="flex justify-between text-xs uppercase text-muted-foreground"><span>{l}</span><I className="h-4 w-4 text-primary"/></div><div className="mt-3 text-2xl font-semibold">{v}</div></CardContent></Card>)}</div>
 <div className="grid xl:grid-cols-2 gap-5"><Card><CardContent className="p-6"><div className="flex justify-between"><div><div className="text-xs uppercase text-muted-foreground">Target</div><div className="mt-1 text-3xl font-semibold">{target}</div></div><Button variant="ghost" onClick={()=>setApplied(false)}><RotateCcw className="mr-2 h-4 w-4"/>Reset</Button></div><div className="mt-5"><div className="text-sm font-medium">First degree impact</div><div className="mt-3 flex flex-wrap gap-2">{applied?result.neighbours.map(n=><Badge key={n} variant="outline">{n}</Badge>):<span className="text-sm text-muted-foreground">Run the perturbation to reveal affected neighbours.</span>}</div></div><div className="mt-6"><div className="text-sm font-medium">Affected pathways</div><div className="mt-3 space-y-2">{applied?result.affectedPathways.map(p=><div className="metric-block" key={p.name}>{p.name}<span className="ml-2 text-xs text-muted-foreground">{p.source}</span></div>):null}</div></div></CardContent></Card>
 <Card><CardContent className="p-6"><Crosshair className="h-5 w-5 text-primary"/><h2 className="mt-3 text-xl font-semibold">Falsification plan</h2>{applied?<div className="mt-4 space-y-4"><p className="text-muted-foreground">If {target} is genuinely structurally important in this context, perturbation should alter at least part of its first degree neighbourhood before broad phenotype changes.</p><div className="metric-block"><div className="text-xs uppercase tracking-wider text-primary">Measure next</div><p className="mt-2 text-sm">Quantify {result.neighbours.slice(0,4).join(", ")||"first degree interactors"} across an early time course with an orthogonal perturbation. Stable neighbours despite successful target modulation would weaken the current network model.</p></div></div>:<p className="mt-4 text-muted-foreground">No interpretation is generated until the deterministic perturbation has run.</p>}</CardContent></Card></div>
 </div></AppLayout>
};
export default Simulate;
