import { useEffect,useMemo,useRef } from "react";import type { CellTypeProfile,ProcessKey } from "@/data/cellAtlas";import type { VisualEffect } from "@/lib/cellEffectMapping";import { makeParticles,type SimParticle } from "@/lib/cellSimulation";
type Props={cell:CellTypeProfile;effects:VisualEffect[];selected:ProcessKey;onSelect:(p:ProcessKey)=>void;paused:boolean;speed:number;diseaseBlend:number;perturbed:string|null};
const colors={rna:"#b997ff",protein:"#f1d28c",vesicle:"#6ee7d2",calcium:"#77bfff",signal:"#ff9a8b",cargo:"#d79c68",atp:"#ffe36e"};
export function CellAtlasCanvas({cell,effects,selected,onSelect,paused,speed,diseaseBlend,perturbed}:Props){const ref=useRef<HTMLCanvasElement>(null),parts=useRef<SimParticle[]>([]);const em=useMemo(()=>new Map(effects.map(e=>[e.process,e])),[effects]);useEffect(()=>{parts.current=makeParticles(cell.processes,Math.min(170,80+cell.processes.length*14))},[cell.id]);
useEffect(()=>{const c=ref.current;if(!c)return;const x=c.getContext("2d");if(!x)return;let raf=0,last=performance.now();const resize=()=>{const r=c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);c.width=r.width*d;c.height=r.height*d;x.setTransform(d,0,0,d,0,0)};resize();const ro=new ResizeObserver(resize);ro.observe(c);
const org:[ProcessKey,number,number,number][]=[["transcription",.47,.43,.15],["mitochondria",.68,.51,.08],["autophagy",.69,.69,.05],["trafficking",.37,.64,.065],["translation",.55,.67,.05]];
const cellShape=(w:number,h:number)=>{const s=Math.min(w,h),cx=w*.5,cy=h*.5;x.save();x.translate(cx,cy);x.strokeStyle="rgba(170,220,238,.34)";x.fillStyle="rgba(80,130,160,.08)";x.lineWidth=1.5;if(cell.morphology==="neuron"){x.lineWidth=s*.03;x.lineCap="round";for(let i=0;i<5;i++){x.beginPath();x.moveTo(-s*.19,(-.17+i*.08)*s);x.quadraticCurveTo(-s*.36,(-.28+i*.1)*s,-s*.46,(-.22+i*.11)*s);x.stroke()}x.beginPath();x.moveTo(s*.18,s*.03);x.bezierCurveTo(s*.35,s*.02,s*.4,s*.2,s*.49,s*.22);x.stroke();x.lineWidth=1.5}x.beginPath();if(cell.morphology==="cardiomyocyte")x.roundRect(-s*.37,-s*.2,s*.74,s*.4,s*.1);else if(cell.morphology==="immune"||cell.morphology==="glia")x.arc(0,0,s*.3,0,Math.PI*2);else x.ellipse(0,0,s*.3,s*.27,0,0,Math.PI*2);x.fill();x.stroke();if(cell.morphology==="cardiomyocyte"){x.strokeStyle="rgba(150,200,220,.15)";for(let q=-.32;q<.34;q+=.055){x.beginPath();x.moveTo(q*s,-.18*s);x.lineTo(q*s,.18*s);x.stroke()}}x.restore()};
const draw=(now:number)=>{const dt=Math.min(.04,(now-last)/1000);last=now;const w=c.clientWidth,h=c.clientHeight,s=Math.min(w,h);x.clearRect(0,0,w,h);cellShape(w,h);org.forEach(([p,ox,oy,r],i)=>{if(!cell.processes.includes(p)&&p!=="transcription")return;const e=em.get(p),pulse=1+(paused?0:Math.sin(now*.001*(1+i*.15))*.05);x.beginPath();if(p==="mitochondria")x.ellipse(w*ox,h*oy,s*r*1.4*pulse,s*r*.65*pulse,-.35,0,Math.PI*2);else x.arc(w*ox,h*oy,s*r*pulse,0,Math.PI*2);x.fillStyle=p===selected?"rgba(105,215,235,.26)":"rgba(145,125,190,.22)";x.fill();x.strokeStyle=p===selected?"rgba(190,245,255,.9)":"rgba(200,220,230,.24)";x.stroke();if(e&&diseaseBlend>.05){x.beginPath();x.arc(w*ox,h*oy,s*r*1.25,0,Math.PI*2);const a=.12+.42*diseaseBlend*e.intensity;x.strokeStyle=e.direction==="increase"?"rgba(255,132,110,"+a+")":"rgba(90,160,255,"+a+")";x.setLineDash([3,5]);x.stroke();x.setLineDash([])}});
if(!paused)parts.current=parts.current.map(p=>{let nx=p.x+p.vx*dt*speed,ny=p.y+p.vy*dt*speed,vx=p.vx,vy=p.vy;if(nx<.08||nx>.92)vx*=-1;if(ny<.08||ny>.92)vy*=-1;return{...p,x:Math.max(.08,Math.min(.92,nx)),y:Math.max(.08,Math.min(.92,ny)),vx,vy}});
parts.current.forEach(p=>{if(!cell.processes.includes(p.process))return;const e=em.get(p.process),a=.22+.58*(e?.intensity??.3)*(p.process===selected?1:.6);x.beginPath();x.arc(p.x*w,p.y*h,p.kind==="calcium"?2.1:1.6,0,Math.PI*2);x.globalAlpha=a;x.fillStyle=colors[p.kind];x.fill();x.globalAlpha=1});if(perturbed){x.fillStyle="rgba(255,196,90,.9)";x.font="11px JetBrains Mono";x.fillText("COUNTERFACTUAL · "+perturbed+" SUPPRESSED",18,30)}raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);ro.disconnect()}},[cell,em,paused,speed,diseaseBlend,selected,perturbed]);
const click=(e:React.MouseEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect(),px=(e.clientX-r.left)/r.width,py=(e.clientY-r.top)/r.height;const hits:[ProcessKey,number,number][]=[["transcription",.47,.43],["mitochondria",.68,.51],["autophagy",.69,.69],["trafficking",.37,.64],["translation",.55,.67]];const hit=hits.filter(h=>cell.processes.includes(h[0])).sort((a,b)=>Math.hypot(px-a[1],py-a[2])-Math.hypot(px-b[1],py-b[2]))[0];if(hit&&Math.hypot(px-hit[1],py-hit[2])<.14)onSelect(hit[0])};return <canvas ref={ref} className="atlas-canvas" onClick={click} aria-label={"Dynamic mechanistic visualisation of "+cell.name}/>}