import { useMemo } from "react";
export type CellRegion={id:string;name:string;subtitle:string;x:number;y:number;rx:number;ry:number;fill:string;pathway:string;signal:number};
export const cellRegions:CellRegion[]=[
{id:"nucleus",name:"Nucleus",subtitle:"Transcriptional control",x:48,y:43,rx:16,ry:19,fill:"#7965b6",pathway:"Gene regulation",signal:86},
{id:"mito-a",name:"Mitochondrion",subtitle:"Energetics · mitophagy",x:67,y:50,rx:11,ry:6,fill:"#d06f55",pathway:"Oxidative phosphorylation",signal:92},
{id:"mito-b",name:"Mitochondrion II",subtitle:"Stress response",x:37,y:62,rx:9,ry:5,fill:"#bb6047",pathway:"Mitophagy",signal:78},
{id:"golgi",name:"Golgi / ER",subtitle:"Protein trafficking",x:59,y:66,rx:8,ry:10,fill:"#d8955b",pathway:"Vesicle transport",signal:64},
{id:"lysosome",name:"Lysosome",subtitle:"Clearance",x:73,y:72,rx:6,ry:6,fill:"#3f9b91",pathway:"Autophagy",signal:71}] ;
export function LivingCell({selected,onSelect}:{selected:string;onSelect:(id:string)=>void}){
const particles=useMemo(()=>Array.from({length:54},(_,i)=>({x:16+((i*37)%70),y:15+((i*53)%70),r:.35+(i%4)*.16})),[]);
return <div className="cell-stage" aria-label="Interactive cellular systems map"><div className="cell-orbit cell-orbit-a"/><div className="cell-orbit cell-orbit-b"/><svg viewBox="0 0 100 100" className="living-cell" role="img"><defs><radialGradient id="cellBody"><stop offset="0%" stopColor="#dbe7ef" stopOpacity=".12"/><stop offset="72%" stopColor="#8ca5b8" stopOpacity=".08"/><stop offset="100%" stopColor="#b9d8e7" stopOpacity=".26"/></radialGradient><filter id="glow"><feGaussianBlur stdDeviation="1.4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><circle cx="50" cy="50" r="39" fill="url(#cellBody)" stroke="#ccecff" strokeOpacity=".28" strokeWidth=".6"/><circle cx="50" cy="50" r="37.8" fill="none" stroke="#8db9cf" strokeOpacity=".18" strokeDasharray="1 1.6"/>{particles.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r={p.r} fill={i%5===0?"#dca36d":"#d6c58e"} opacity={.28+(i%3)*.12}/>)}<path d="M42 30 C55 35 58 43 62 58 S69 73 75 80" fill="none" stroke="#c6d8df" strokeOpacity=".2" strokeWidth="1.1"/><path d="M38 32 C50 38 51 52 55 70" fill="none" stroke="#c6d8df" strokeOpacity=".16" strokeWidth=".7"/>{cellRegions.map(r=><g key={r.id} className={"organelle "+(selected===r.id?"is-selected":"")} onClick={()=>onSelect(r.id)} tabIndex={0} role="button" onKeyDown={e=>{if(e.key==="Enter")onSelect(r.id)}}><ellipse cx={r.x} cy={r.y} rx={r.rx} ry={r.ry} fill={r.fill} opacity=".74" filter="url(#glow)" transform={r.id.startsWith("mito")?"rotate(-18 "+r.x+" "+r.y+")":undefined}/>{r.id.startsWith("mito")&&<path d={"M"+(r.x-7)+" "+r.y+" q3 -4 6 0 t6 0"} fill="none" stroke="#ffd0b6" strokeOpacity=".65" strokeWidth=".7"/>}<circle cx={r.x} cy={r.y} r={Math.max(r.rx,r.ry)+2.2} fill="none" stroke="#bdf3ff" strokeOpacity={selected===r.id?.9:0} strokeWidth=".5" strokeDasharray="1.4 1.4"/></g>)}</svg><div className="cell-scanline"/></div>}
